// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: book/book.proto

package book

import (
	book "demo/pb/book"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Book struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Title string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// 应用price.proto
	Price         *book.Price            `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	Name          *Info                  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_book_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetPrice() *book.Price {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Book) GetName() *Info {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Book) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

var File_book_book_proto protoreflect.FileDescriptor

const file_book_book_proto_rawDesc = "" +
	"\n" +
	"\x0fbook/book.proto\x12\x04book\x1a\x10book/price.proto\x1a\x13author/author.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x91\x01\n" +
	"\x04Book\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12!\n" +
	"\x05price\x18\x02 \x01(\v2\v.book.PriceR\x05price\x12 \n" +
	"\x04name\x18\x03 \x01(\v2\f.author.InfoR\x04name\x12.\n" +
	"\x04date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04date23\n" +
	"\vBookService\x12$\n" +
	"\n" +
	"CreateBook\x12\n" +
	".book.Book\x1a\n" +
	".book.BookB\x11Z\x0fdemo/proto/bookb\x06proto3"

var (
	file_book_book_proto_rawDescOnce sync.Once
	file_book_book_proto_rawDescData []byte
)

func file_book_book_proto_rawDescGZIP() []byte {
	file_book_book_proto_rawDescOnce.Do(func() {
		file_book_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_book_book_proto_rawDesc), len(file_book_book_proto_rawDesc)))
	})
	return file_book_book_proto_rawDescData
}

var file_book_book_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_book_book_proto_goTypes = []any{
	(*Book)(nil),                  // 0: book.Book
	(*book.Price)(nil),            // 1: book.Price
	(*Info)(nil),                  // 2: author.Info
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_book_book_proto_depIdxs = []int32{
	1, // 0: book.Book.price:type_name -> book.Price
	2, // 1: book.Book.name:type_name -> author.Info
	3, // 2: book.Book.date:type_name -> google.protobuf.Timestamp
	0, // 3: book.BookService.CreateBook:input_type -> book.Book
	0, // 4: book.BookService.CreateBook:output_type -> book.Book
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_book_book_proto_init() }
func file_book_book_proto_init() {
	if File_book_book_proto != nil {
		return
	}
	file_author_author_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_book_book_proto_rawDesc), len(file_book_book_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_book_book_proto_goTypes,
		DependencyIndexes: file_book_book_proto_depIdxs,
		MessageInfos:      file_book_book_proto_msgTypes,
	}.Build()
	File_book_book_proto = out.File
	file_book_book_proto_goTypes = nil
	file_book_book_proto_depIdxs = nil
}
